spring.application.name=demo
# 1. Añadir 'jdbc:' al inicio y dejar solo el host, puerto y nombre de BD
spring.datasource.url=jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:6543/postgres

# 2. El usuario va en su propia propiedad
spring.datasource.username=postgres.vjjnfgqjdxmloxvplarp

# 3. La contraseña va en su propia propiedad
spring.datasource.password=yeahbaby15975312ad

# 4. Driver explícito
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA (Mantenla como la tenías)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true